# Generated by Django 3.2.5 on 2021-07-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210701_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rib',
            field=models.CharField(default='MA64230090334232779901260011', max_length=28),
        ),
    ]
